package vista.view;


import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;




public class VMaterias extends javax.swing.JFrame {
  
    /**
     * Creates new form VEstudiante
     */
    private Principal menu;
    
    public VMaterias(Principal menu) {
        this.menu = menu;
        initComponents();
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCodigoMate = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMateria = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCreditos = new javax.swing.JTextField();
        btnBuscarMate = new javax.swing.JButton();
        btnRegistrarMate = new javax.swing.JButton();
        btnModificarMate = new javax.swing.JButton();
        btnEliminarMate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMate = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro Estudiantil");
        setBackground(new java.awt.Color(0, 0, 153));

        txtCodigoMate.addActionListener(this::txtCodigoMateActionPerformed);

        jLabel1.setText("Codigo: ");

        jLabel2.setText("Materia:");

        jLabel3.setText("Creditos: ");

        btnBuscarMate.setText("Buscar");
        btnBuscarMate.addActionListener(this::btnBuscarMateActionPerformed);

        btnRegistrarMate.setText("Registrar");

        btnModificarMate.setText("Modificar");
        btnModificarMate.addActionListener(this::btnModificarMateActionPerformed);

        btnEliminarMate.setText("Eliminar");
        btnEliminarMate.addActionListener(this::btnEliminarMateActionPerformed);

        jTableMate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo", "Materia", "Creditos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableMate.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableMate);
        if (jTableMate.getColumnModel().getColumnCount() > 0) {
            jTableMate.getColumnModel().getColumn(0).setResizable(false);
            jTableMate.getColumnModel().getColumn(1).setResizable(false);
            jTableMate.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel6.setBackground(new java.awt.Color(255, 0, 0));
        jLabel6.setFont(new java.awt.Font("Dubai", 3, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("Registro Materias");
        jLabel6.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jLabel6.setMaximumSize(new java.awt.Dimension(101, 20));

        btnVolver.setText("Volver al menu");
        btnVolver.addActionListener(this::btnVolverActionPerformed);
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCodigoMate, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(37, 37, 37)
                                .addComponent(btnBuscarMate))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnVolver)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnRegistrarMate)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnModificarMate)
                                        .addGap(7, 7, 7)
                                        .addComponent(btnEliminarMate)))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodigoMate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(btnBuscarMate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegistrarMate)
                            .addComponent(btnModificarMate)
                            .addComponent(btnEliminarMate))
                        .addGap(195, 195, 195)
                        .addComponent(btnVolver)
                        .addGap(48, 48, 48))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarMateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarMateActionPerformed

    private void btnModificarMateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarMateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarMateActionPerformed

    private void btnEliminarMateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarMateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarMateActionPerformed

    private void txtCodigoMateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoMateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoMateActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
    menu.setVisible(true);
    menu.setLocationRelativeTo(null);
    this.dispose();

        
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */

    }

    public JButton getBtnBuscarMate() {
        return btnBuscarMate;
    }

    public void setBtnBuscarMate(JButton btnBuscarMate) {
        this.btnBuscarMate = btnBuscarMate;
    }

    public JButton getBtnEliminarMate() {
        return btnEliminarMate;
    }

    public void setBtnEliminarMate(JButton btnEliminarMate) {
        this.btnEliminarMate = btnEliminarMate;
    }

    public JButton getBtnModificar1() {
        return btnVolver;
    }

    public void setBtnModificar1(JButton btnModificar1) {
        this.btnVolver = btnModificar1;
    }

    public JButton getBtnModificarMate() {
        return btnModificarMate;
    }

    public void setBtnModificarMate(JButton btnModificarMate) {
        this.btnModificarMate = btnModificarMate;
    }

    public JButton getBtnRegistrarMate() {
        return btnRegistrarMate;
    }

    public void setBtnRegistrarMate(JButton btnRegistrarMate) {
        this.btnRegistrarMate = btnRegistrarMate;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JTable getjTableMate() {
        return jTableMate;
    }

    public void setjTableMate(JTable jTableMate) {
        this.jTableMate = jTableMate;
    }

    public JTextField getTxtCodigoMate() {
        return txtCodigoMate;
    }

    public void setTxtCodigoMate(JTextField txtCodigoMate) {
        this.txtCodigoMate = txtCodigoMate;
    }

    public JTextField getTxtCreditos() {
        return txtCreditos;
    }

    public void setTxtCreditos(JTextField txtCreditos) {
        this.txtCreditos = txtCreditos;
    }

    public JTextField getTxtMateria() {
        return txtMateria;
    }

    public void setTxtMateria(JTextField txtMateria) {
        this.txtMateria = txtMateria;
    }


    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarMate;
    private javax.swing.JButton btnEliminarMate;
    private javax.swing.JButton btnModificarMate;
    private javax.swing.JButton btnRegistrarMate;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMate;
    private javax.swing.JTextField txtCodigoMate;
    private javax.swing.JTextField txtCreditos;
    private javax.swing.JTextField txtMateria;
    // End of variables declaration//GEN-END:variables

   

}





