package vista.view;


import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;


public class VProfesores extends javax.swing.JFrame {

    public static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VProfesores.class.getName());

    /**
     * Creates new form VEstudiante
     */
    public VProfesores(Principal menu) {
        this.menu = menu;
        initComponents();
    }
    private Principal menu;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtIdProf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombreProf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtApellidoProf = new javax.swing.JTextField();
        btnBuscarProf = new javax.swing.JButton();
        btnRegistrarProf = new javax.swing.JButton();
        btnModificarProf = new javax.swing.JButton();
        btnEliminarProf = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaProf = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        btnVolverProf = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro Estudiantil");
        setBackground(new java.awt.Color(0, 0, 153));

        txtIdProf.addActionListener(this::txtIdProfActionPerformed);

        jLabel1.setText("ID: ");

        jLabel2.setText("Nombre: ");

        jLabel3.setText("Apellido: ");

        btnBuscarProf.setText("Buscar");
        btnBuscarProf.addActionListener(this::btnBuscarProfActionPerformed);

        btnRegistrarProf.setText("Registrar");

        btnModificarProf.setText("Modificar");
        btnModificarProf.addActionListener(this::btnModificarProfActionPerformed);

        btnEliminarProf.setText("Eliminar");
        btnEliminarProf.addActionListener(this::btnEliminarProfActionPerformed);

        TablaProf.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Apellido", "Materia"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaProf);
        if (TablaProf.getColumnModel().getColumnCount() > 0) {
            TablaProf.getColumnModel().getColumn(0).setResizable(false);
            TablaProf.getColumnModel().getColumn(1).setResizable(false);
            TablaProf.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel6.setBackground(new java.awt.Color(255, 0, 0));
        jLabel6.setFont(new java.awt.Font("Dubai", 3, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("Registro Profesor");
        jLabel6.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jLabel6.setMaximumSize(new java.awt.Dimension(101, 20));

        btnVolverProf.setText("Volver al menu");
        btnVolverProf.addActionListener(this::btnVolverProfActionPerformed);
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtApellidoProf, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNombreProf, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtIdProf, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(37, 37, 37)
                                .addComponent(btnBuscarProf))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnVolverProf)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnRegistrarProf)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnModificarProf)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnEliminarProf)))))
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(28, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(btnBuscarProf))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApellidoProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegistrarProf)
                            .addComponent(btnModificarProf)
                            .addComponent(btnEliminarProf))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVolverProf)
                        .addGap(72, 72, 72))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarProfActionPerformed

    private void btnModificarProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarProfActionPerformed

    private void btnEliminarProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarProfActionPerformed

    private void txtIdProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdProfActionPerformed

    private void btnVolverProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverProfActionPerformed
    menu.setVisible(true);
    menu.setLocationRelativeTo(null);
    this.dispose();
    }//GEN-LAST:event_btnVolverProfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
   
    
}
    public JTable getTablaProf() {
        return TablaProf;
    }

    public void setTablaProf(JTable TablaProf) {
        this.TablaProf = TablaProf;
    }

    public JButton getBtnBuscarProf() {
        return btnBuscarProf;
    }

    public void setBtnBuscarProf(JButton btnBuscarProf) {
        this.btnBuscarProf = btnBuscarProf;
    }

    public JButton getBtnEliminarProf() {
        return btnEliminarProf;
    }

    public void setBtnEliminarProf(JButton btnEliminarProf) {
        this.btnEliminarProf = btnEliminarProf;
    }

    public JButton getBtnModificarProf() {
        return btnModificarProf;
    }

    public void setBtnModificarProf(JButton btnModificarProf) {
        this.btnModificarProf = btnModificarProf;
    }

    public JButton getBtnRegistrarProf() {
        return btnRegistrarProf;
    }

    public void setBtnRegistrarProf(JButton btnRegistrarProf) {
        this.btnRegistrarProf = btnRegistrarProf;
    }

    public JButton getBtnVolverProf() {
        return btnVolverProf;
    }

    public void setBtnVolverProf(JButton btnVolverProf) {
        this.btnVolverProf = btnVolverProf;
    }

    public JTextField getTxtApellidoProf() {
        return txtApellidoProf;
    }

    public void setTxtApellidoProf(JTextField txtApellidoProf) {
        this.txtApellidoProf = txtApellidoProf;
    }

    public JTextField getTxtIdProf() {
        return txtIdProf;
    }

    public void setTxtIdProf(JTextField txtIdProf) {
        this.txtIdProf = txtIdProf;
    }

    public JTextField getTxtNombreProf() {
        return txtNombreProf;
    }

    public void setTxtNombreProf(JTextField txtNombreProf) {
        this.txtNombreProf = txtNombreProf;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaProf;
    private javax.swing.JButton btnBuscarProf;
    private javax.swing.JButton btnEliminarProf;
    private javax.swing.JButton btnModificarProf;
    private javax.swing.JButton btnRegistrarProf;
    private javax.swing.JButton btnVolverProf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtApellidoProf;
    private javax.swing.JTextField txtIdProf;
    private javax.swing.JTextField txtNombreProf;
    // End of variables declaration//GEN-END:variables

}

